решение первой задачи
js-tasks-ru/jsbasic-20240708-2_konstantin-dudukin-00 pull request #1
Opened 2024-06-04 19:01 UTC by KonstantinBerg

2024-06-04 19:01 UTC, jsru-1 commented
Спасибо за отправленный пулриквест, теперь @koalex должен запустить тесты.

2024-06-05 03:08 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-06-05 03:09 UTC, koalex requested changes
Не решена **1-1**

2024-07-13 15:22 UTC, KonstantinBerg commented
Здравствуйте, @koalex все решил и добавил

2024-07-13 16:04 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-07-13 16:20 UTC, koalex approved these changes

2024-07-13 16:20 UTC, koalex commented on 1-module/2-task/index.js
> +  if (name && name.length >= 4 && name.indexOf(' ') == -1) {
`return name && name.length >= 4 && name.indexOf(' ') == -1;`

2024-07-13 16:21 UTC, merged